apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-backend
  namespace: taskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskapp-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: taskapp-backend
    spec:
      containers:
      - name: taskapp-backend
        image: 493608842618.dkr.ecr.us-east-1.amazonaws.com/taskapp-backend:f4d514ed3ededa92ba4bc234845d30096f93cf68
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "526Mi"
            cpu: "250m"
          limits:
            memory: "526Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20